version: "2"

plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
  sonar-php:
    enabled: true
  fixme:
    enabled: true

exclude_patterns:
  - .hgignore
  - LICENSE
  - README.md
  - build.xml
  - composer.json
  - libchart/doc/GNU_GPL_V3
  - libchart/doc/DEJAVU_LICENSE
  - libchart/README
  - "**/*.ttf"
  - "**/*.png"
