version: "2"

plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
  sonar-php:
    enabled: true
  fixme:
    enabled: true

exclude_patterns:
  - "**/test/"
  - "**/tests/"
  - .hgignore
  - LICENSE
  - README.md
  - build.xml
  - phpunit.xml
  - composer.json
  - libchart/doc/GNU_GPL_V3
  - libchart/doc/DEJAVU_LICENSE
  - libchart/ChangeLog
  - libchart/COPYING
  - libchart/README
  - "**/*.ttf"
  - "**/*.png"
  - ".codeclimate.yml"
  - ".gitignore"
  - ".travis.yml"
  - "**/.travis/*.sh"
